version: '3.8'
services:

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL : andres.lozano@amarilo.com
      PGADMIN_DEFAULT_PASSWORD : amarilo
    ports:
      - "80:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   stdin_open: true
  #   tty: true
  #   depends_on: 
  #     - backend