version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL : andres.lozano@amarilo.com
      PGADMIN_DEFAULT_PASSWORD : amarilo
    ports:
      - "80:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

