# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - PruebaIntegra

on:
  push:
    branches:
      - master
    paths-ignore:
    - "README.md"
    - ".next"
    - .env*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/frontend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ${{ github.workspace }}/frontend
        
      - name: Zip all files for upload between jobs
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        run: zip next.zip ./* .next .env -qr
        
      - name: List files in the repository
        run: |
            ls ${{ github.workspace }}/frontend       
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: next.zip    
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/frontend
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      - name: Test Artifact Download Next
        run: ls -R 
      - name: unzip artifact for deployment
        run: unzip next.zip
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'PruebaIntegra'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BDBE9383A19D4967AE08BF44EC048754 }}
          package: next.zip
          
      - name: Delete zip file
        run: rm next.zip
